name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    if: github.ref == 'refs/heads/master' 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update stable tag
      uses: ncipollo/release-action@v1
      with:
        name: Release ${{ github.ref }}
        tag: stable
        draft: false
        prerelease: false
        allowUpdates: true
        token: ${{ secrets.GITHUB_TOKEN }}
